version: "4.8"

services:
  postgres:
    image: postgres:latest
    container_name: growfuse
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog:latest
    container_name: growuse_mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI to view emails

volumes:
  postgres_data:
